### ISSUE TITLE
Failing builds with MongoID 6.0 on Travis

### ISSUE THREAD

**Issue by lwe** [lwe/simple_enum#143]
Recently I've noticed that we have failing builds on Travis CI.

It seems that this merge, did fail with the latest mongoid version:
https://travis-ci.org/lwe/simple_enum/builds/364547603

Error messages are all like:

```
  8) SimpleEnum::Attribute generate_enum_scope_methods_for when pluralize scopes option is set to false .female behaves like delegates to accessor#scope delegates to #scope
     Failure/Error: subject { klass.female }
       gender received :scope with unexpected arguments
         expected: (#<Class:0x000000051d79f0>(id: integer, name: string, gender_cd: integer, word_cd: string, role_cd: string, other: integer, numeric_cd: string, nilish_cd: string, style_cd: integer), 1)
              got: (#<ActiveRecord::Relation []>, 1)
     Shared Example Group: "delegates to accessor#scope" called from ./spec/simple_enum/attribute_spec.rb:256
     # ./lib/simple_enum/attribute.rb:92:in `block (2 levels) in generate_enum_scope_methods_for'
     # ./spec/simple_enum/attribute_spec.rb:255:in `block (5 levels) in <top (required)>'
     # ./spec/simple_enum/attribute_spec.rb:198:in `block (4 levels) in <top (required)>'
```

**Comment by drobny** [comment]
@lwe https://github.com/lwe/simple_enum/pull/145 should fix this unless you can see any issue with doing it this way?

**Comment by drobny** [comment]
Fixed by https://github.com/lwe/simple_enum/pull/145

**Comment by lwe** [comment]
Thanks 👍
